In [1]:
# 残高がゼロになるまで繰り返す
shikin = 50000
while(shikin >= 0){
    print(shikin)
    shikin <- shikin - 5080
}

[1] 50000
[1] 44920
[1] 39840
[1] 34760
[1] 29680
[1] 24600
[1] 19520
[1] 14440
[1] 9360
[1] 4280

In [2]:
 # 同じメッセージを10回表示する
for(i in 1:10){
    print("ハロー！")
}

[1] "ハロー！"
[1] "ハロー！"
[1] "ハロー！"
[1] "ハロー！"
[1] "ハロー！"
[1] "ハロー！"
[1] "ハロー！"
[1] "ハロー！"
[1] "ハロー！"
[1] "ハロー！"

In [5]:
# メッセージの中に回数を入れる
for(i in 1:10){
    print(paste(i,"回目のハロー！",sep=""))
}

[1] "1回目のハロー！"
[1] "2回目のハロー！"
[1] "3回目のハロー！"
[1] "4回目のハロー！"
[1] "5回目のハロー！"
[1] "6回目のハロー！"
[1] "7回目のハロー！"
[1] "8回目のハロー！"
[1] "9回目のハロー！"
[1] "10回目のハロー！"

In [6]:
# 逆順で繰り返すには
for(i in 10:1){
    print(paste(i,"回目のハロー！",sep=""))
}

[1] "10回目のハロー！"
[1] "9回目のハロー！"
[1] "8回目のハロー！"
[1] "7回目のハロー！"
[1] "6回目のハロー！"
[1] "5回目のハロー！"
[1] "4回目のハロー！"
[1] "3回目のハロー！"
[1] "2回目のハロー！"
[1] "1回目のハロー！"

In [7]:
# 九九の計算をしてみよう
for(x in 1:9){
    for(y in 1:9){
        print(x*y)
    }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 2
[1] 4
[1] 6
[1] 8
[1] 10
[1] 12
[1] 14
[1] 16
[1] 18
[1] 3
[1] 6
[1] 9
[1] 12
[1] 15
[1] 18
[1] 21
[1] 24
[1] 27
[1] 4
[1] 8
[1] 12
[1] 16
[1] 20
[1] 24
[1] 28
[1] 32
[1] 36
[1] 5
[1] 10
[1] 15
[1] 20
[1] 25
[1] 30
[1] 35
[1] 40
[1] 45
[1] 6
[1] 12
[1] 18
[1] 24
[1] 30
[1] 36
[1] 42
[1] 48
[1] 54
[1] 7
[1] 14
[1] 21
[1] 28
[1] 35
[1] 42
[1] 49
[1] 56
[1] 63
[1] 8
[1] 16
[1] 24
[1] 32
[1] 40
[1] 48
[1] 56
[1] 64
[1] 72
[1] 9
[1] 18
[1] 27
[1] 36
[1] 45
[1] 54
[1] 63
[1] 72
[1] 81

In [9]:
# 九九らしく表示する
for(x in 1:9){
    for(y in 1:9){
        print(paste(x,"×",y,"＝",x*y))
    }
}

[1] "1 × 1 ＝ 1"
[1] "1 × 2 ＝ 2"
[1] "1 × 3 ＝ 3"
[1] "1 × 4 ＝ 4"
[1] "1 × 5 ＝ 5"
[1] "1 × 6 ＝ 6"
[1] "1 × 7 ＝ 7"
[1] "1 × 8 ＝ 8"
[1] "1 × 9 ＝ 9"
[1] "2 × 1 ＝ 2"
[1] "2 × 2 ＝ 4"
[1] "2 × 3 ＝ 6"
[1] "2 × 4 ＝ 8"
[1] "2 × 5 ＝ 10"
[1] "2 × 6 ＝ 12"
[1] "2 × 7 ＝ 14"
[1] "2 × 8 ＝ 16"
[1] "2 × 9 ＝ 18"
[1] "3 × 1 ＝ 3"
[1] "3 × 2 ＝ 6"
[1] "3 × 3 ＝ 9"
[1] "3 × 4 ＝ 12"
[1] "3 × 5 ＝ 15"
[1] "3 × 6 ＝ 18"
[1] "3 × 7 ＝ 21"
[1] "3 × 8 ＝ 24"
[1] "3 × 9 ＝ 27"
[1] "4 × 1 ＝ 4"
[1] "4 × 2 ＝ 8"
[1] "4 × 3 ＝ 12"
[1] "4 × 4 ＝ 16"
[1] "4 × 5 ＝ 20"
[1] "4 × 6 ＝ 24"
[1] "4 × 7 ＝ 28"
[1] "4 × 8 ＝ 32"
[1] "4 × 9 ＝ 36"
[1] "5 × 1 ＝ 5"
[1] "5 × 2 ＝ 10"
[1] "5 × 3 ＝ 15"
[1] "5 × 4 ＝ 20"
[1] "5 × 5 ＝ 25"
[1] "5 × 6 ＝ 30"
[1] "5 × 7 ＝ 35"
[1] "5 × 8 ＝ 40"
[1] "5 × 9 ＝ 45"
[1] "6 × 1 ＝ 6"
[1] "6 × 2 ＝ 12"
[1] "6 × 3 ＝ 18"
[1] "6 × 4 ＝ 24"
[1] "6 × 5 ＝ 30"
[1] "6 × 6 ＝ 36"
[1] "6 × 7 ＝ 42"
[1] "6 × 8 ＝ 48"
[1] "6 × 9 ＝ 54"
[1] "7 × 1 ＝ 7"
[1] "7 × 2 ＝ 14"
[1] "7 × 3 ＝ 21"
[1] "7 × 4 ＝ 28"
[1] "7 × 5 ＝ 35"
[1] "7 × 6 ＝ 42"
[1] "7 × 7 ＝ 49"
[1] "7 × 8 ＝ 56"
[1] "7 × 9 ＝ 63"
[1] "8 × 1 ＝ 8"
[1] "8 × 2 ＝ 16"
[1] "8 × 3 ＝ 24"
[1] "8 × 4 ＝ 32"
[1] "8 × 5 ＝ 40"
[1] "8 × 6 ＝ 48"
[1] "8 × 7 ＝ 56"
[1] "8 × 8 ＝ 64"
[1] "8 × 9 ＝ 72"
[1] "9 × 1 ＝ 9"
[1] "9 × 2 ＝ 18"
[1] "9 × 3 ＝ 27"
[1] "9 × 4 ＝ 36"
[1] "9 × 5 ＝ 45"
[1] "9 × 6 ＝ 54"
[1] "9 × 7 ＝ 63"
[1] "9 × 8 ＝ 72"
[1] "9 × 9 ＝ 81"

In [13]:
# 配列* を作って利用する
wdays <- c('月', '火', '水', '木', '金')
print(wdays[2])

[1] "火"

In [16]:
# 配列の要素を書き替える
wdays <- c('月', '火', '水', '木', '金')
wdays[2] <- "炎"
print(wdays);

[1] "月" "炎" "水" "木" "金"

In [19]:
# for文を使ってインデックスを指定する
wdays <- c('月', '火', '水', '木', '金')
for(i in 1:5){
print(paste(wdays[i],"曜日",sep=""));
}

[1] "月曜日"
[1] "火曜日"
[1] "水曜日"
[1] "木曜日"
[1] "金曜日"

In [20]:
# 単純にすべての組み合わせを並べる
team <- c('A', 'B', 'C', 'D', 'E')
for(t1 in team){
    for(t2 in team){
        print(paste(t1,' vs ',t2))
    }
}

[1] "A  vs  A"
[1] "A  vs  B"
[1] "A  vs  C"
[1] "A  vs  D"
[1] "A  vs  E"
[1] "B  vs  A"
[1] "B  vs  B"
[1] "B  vs  C"
[1] "B  vs  D"
[1] "B  vs  E"
[1] "C  vs  A"
[1] "C  vs  B"
[1] "C  vs  C"
[1] "C  vs  D"
[1] "C  vs  E"
[1] "D  vs  A"
[1] "D  vs  B"
[1] "D  vs  C"
[1] "D  vs  D"
[1] "D  vs  E"
[1] "E  vs  A"
[1] "E  vs  B"
[1] "E  vs  C"
[1] "E  vs  D"
[1] "E  vs  E"

In [21]:
team <- c('A', 'B', 'C', 'D', 'E')
for(t1 in team){
    for(t2 in team){
        if(t1 != t2){
            print(paste(t1,' vs ',t2))
        }
    }
}

[1] "A  vs  B"
[1] "A  vs  C"
[1] "A  vs  D"
[1] "A  vs  E"
[1] "B  vs  A"
[1] "B  vs  C"
[1] "B  vs  D"
[1] "B  vs  E"
[1] "C  vs  A"
[1] "C  vs  B"
[1] "C  vs  D"
[1] "C  vs  E"
[1] "D  vs  A"
[1] "D  vs  B"
[1] "D  vs  C"
[1] "D  vs  E"
[1] "E  vs  A"
[1] "E  vs  B"
[1] "E  vs  C"
[1] "E  vs  D"

In [30]:
# 同じ対戦組み合わせを省くには？
team <- c('A', 'B', 'C', 'D', 'E')
opps <- c('A', 'B', 'C', 'D', 'E')
for(t1 in team){
    opps <- opps[-1]
    for(t2 in opps){
        print(paste(t1,' vs ',t2))
    }
}

[1] "A  vs  B"
[1] "A  vs  C"
[1] "A  vs  D"
[1] "A  vs  E"
[1] "B  vs  C"
[1] "B  vs  D"
[1] "B  vs  E"
[1] "C  vs  D"
[1] "C  vs  E"
[1] "D  vs  E"